from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ToolCall:
    """A request generated by the model to invoke a tool."""

    name: str
    arguments: dict[str, Any]


@dataclass(frozen=True)
class AgentDecision:
    """Represents the model's next requested action."""

    final_answer: str | None = None
    tool_call: ToolCall | None = None

    def __post_init__(self) -> None:
        has_answer = self.final_answer is not None
        has_tool_call = self.tool_call is not None
        if has_answer == has_tool_call:
            raise ValueError(
                "AgentDecision must contain exactly one of "
                "'final_answer' or 'tool_call'."
            )